import { FilesetResolver, HandLandmarker, FaceLandmarker } from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/+esm';

const $ = (id) => document.getElementById(id);
const video=$('camera'), canvas=$('overlay'), ctx=canvas.getContext('2d');
const ui={landing:$('landing'),loading:$('loading'),error:$('error'),errorText:$('errorText'),live:$('liveUI'),debug:$('debug')};
const debugMode=new URLSearchParams(location.search).get('debug')==='true';
let stream=null, handLandmarker=null, faceLandmarker=null, raf=0, facingMode='user', soundOn=false;
let bloom=0, anchor={x:.5,y:.68}, wind=0, palmLatch=false, lastVideo=-1, lastTime=performance.now();
let particles=[], cinematicUntil=0, blinkTimes=[], lastBlink=false, lastNose=null;
const butterfly={x:-.1,y:.4,tx:.5,ty:.35,state:'entering',restUntil:0,phase:0};
const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const p=(lm)=>({x:1-lm.x,y:lm.y});

function show(name){Object.values(ui).forEach(el=>el?.classList.add('hidden'));ui[name]?.classList.remove('hidden')}
function resize(){const dpr=Math.min(devicePixelRatio,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize,{passive:true});resize();

async function initModels(){
  const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm');
  [handLandmarker,faceLandmarker]=await Promise.all([
    HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.55,minHandPresenceConfidence:.5,minTrackingConfidence:.5}),
    FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:true,minFaceDetectionConfidence:.5,minFacePresenceConfidence:.5,minTrackingConfidence:.5})
  ]);
}
async function start(){
  try{show('loading');
    if(!navigator.mediaDevices?.getUserMedia)throw new Error('This browser does not support camera access.');
    stream=await navigator.mediaDevices.getUserMedia({video:{facingMode,width:{ideal:1280},height:{ideal:720}},audio:false});
    video.srcObject=stream;await new Promise((res,rej)=>{video.onloadedmetadata=res;video.onerror=()=>rej(new Error('Camera preview failed.'))});await video.play();
    await initModels();show('live');lastTime=performance.now();raf=requestAnimationFrame(loop);
  }catch(e){stop();ui.errorText.textContent=e?.message||'Unable to start the camera.';show('error')}
}
function stop(){cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());stream=null;handLandmarker?.close();faceLandmarker?.close();handLandmarker=faceLandmarker=null;ctx.clearRect(0,0,innerWidth,innerHeight)}
function burst(count){for(let i=0;i<count;i++)particles.push({x:anchor.x+(Math.random()-.5)*.12,y:anchor.y-.12+Math.random()*.1,vx:(Math.random()-.5)*.12+wind*.06,vy:-.03-Math.random()*.09,life:.8+Math.random()*1.5,kind:Math.random()>.35?'petal':'pollen'})}
function updateTracking(now,dt){
  if(video.readyState<2||video.currentTime===lastVideo)return;lastVideo=video.currentTime;
  const hr=handLandmarker.detectForVideo(video,now),fr=faceLandmarker.detectForVideo(video,now);
  const hands=hr.landmarks.map((landmarks,i)=>{const raw=hr.handedness[i]?.[0]?.categoryName==='Left'?'Left':'Right';return{handedness:raw==='Left'?'Right':'Left',landmarks}});
  const left=hands.find(h=>h.handedness==='Left'),right=hands.find(h=>h.handedness==='Right');
  if(left){const thumb=p(left.landmarks[4]),index=p(left.landmarks[8]),wrist=p(left.landmarks[0]),middle=p(left.landmarks[9]);const n=dist(thumb,index)/Math.max(.04,dist(wrist,middle));const target=clamp((n-.2)/.75);bloom=lerp(bloom,target,1-Math.pow(.001,dt));anchor.x=lerp(anchor.x,(thumb.x+index.x)/2,.18);anchor.y=lerp(anchor.y,(thumb.y+index.y)/2,.18)}else bloom=lerp(bloom,0,.025);
  if(right){const wrist=p(right.landmarks[0]),mid=p(right.landmarks[12]);wind=lerp(wind,(mid.x-wrist.x)*2.8,.12);const open=[8,12,16,20].filter(i=>dist(p(right.landmarks[i]),wrist)>dist(p(right.landmarks[i-3]),wrist)*1.45).length>=3;if(open&&!palmLatch)burst(14);palmLatch=open}else wind*=.94;
  const faceLm=fr.faceLandmarks[0];if(faceLm){const nose=p(faceLm[1]||faceLm[4]);if(lastNose&&dist(nose,lastNose)>.045&&butterfly.state==='resting'){butterfly.state='startled';butterfly.tx=clamp(nose.x+(nose.x>.5?.35:-.35),.05,.95);butterfly.ty=clamp(nose.y-.25,.05,.9)}lastNose=nose;
    const blends={};fr.faceBlendshapes[0]?.categories.forEach(c=>blends[c.categoryName]=c.score);const blink=((blends.eyeBlinkLeft||0)+(blends.eyeBlinkRight||0))/2>.65;if(blink&&!lastBlink){blinkTimes.push(now);blinkTimes=blinkTimes.filter(t=>now-t<900);if(blinkTimes.length>=2){cinematicUntil=now+4200;burst(30);blinkTimes=[]}}lastBlink=blink;updateButterfly(nose,now,dt)}else updateButterfly({x:.5,y:.35},now,dt);
}
function updateButterfly(nose,time,dt){const b=butterfly;b.phase+=dt;if(b.state==='entering'&&b.x>.15){b.state='flowers';b.tx=anchor.x;b.ty=anchor.y-.15}if(b.state==='flowers'&&Math.random()<.006){b.state='orbiting';b.tx=clamp(nose.x+(Math.random()-.5)*.4,.1,.9);b.ty=clamp(nose.y-.15+(Math.random()-.5)*.25,.08,.75)}if(b.state==='orbiting'&&Math.random()<.008){b.state='approaching';b.tx=nose.x;b.ty=nose.y-.018}if(b.state==='approaching'&&dist(b,{x:b.tx,y:b.ty})<.025){b.state='resting';b.restUntil=time+1500+Math.random()*2200}if(b.state==='resting'){b.tx=nose.x;b.ty=nose.y-.018;if(time>b.restUntil){b.state='flowers';b.tx=anchor.x+.08;b.ty=anchor.y-.2}}if(b.state==='startled'&&dist(b,{x:b.tx,y:b.ty})<.05){b.state='flowers';b.tx=anchor.x;b.ty=anchor.y-.18}if(b.state!=='resting'){b.tx+=Math.sin(b.phase*2.2)*.0009;b.ty+=Math.cos(b.phase*2.7)*.0007}const speed=b.state==='startled'?.14:b.state==='resting'?.3:.045;b.x=lerp(b.x,b.tx,1-Math.pow(.001,dt*speed));b.y=lerp(b.y,b.ty,1-Math.pow(.001,dt*speed))}
function updateParticles(dt){for(const q of particles){q.vy+=.035*dt;q.vx+=wind*.008*dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt}particles=particles.filter(q=>q.life>0&&q.y<1.2)}
function drawFlower(cx,cy,size,progress,cinematic){const pr=clamp(progress);if(pr<=0)return;ctx.save();ctx.translate(cx,cy);ctx.globalCompositeOperation='screen';const glow=ctx.createRadialGradient(0,0,0,0,0,size*1.8);glow.addColorStop(0,`rgba(255,0,45,${(cinematic?.25:.13)*pr})`);glow.addColorStop(1,'rgba(255,0,40,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(0,0,size*1.8,0,Math.PI*2);ctx.fill();ctx.globalCompositeOperation='source-over';for(let i=0;i<12;i++){const a=Math.PI*2*i/12+Math.sin(i*7.1)*.09,len=size*(.45+.85*pr)*(i%3===0?1.12:1);ctx.save();ctx.rotate(a);ctx.strokeStyle=`rgba(255,28,55,${.55+.4*pr})`;ctx.lineWidth=4.8;ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(len*.25,-size*.28,len*.58,size*.4,len,-size*.1*(1-pr));ctx.stroke();ctx.strokeStyle='rgba(255,105,125,.7)';ctx.lineWidth=1.1;ctx.stroke();ctx.restore()}if(pr>.48){const sp=clamp((pr-.48)/.52);for(let i=0;i<18;i++){const a=Math.PI*2*i/18+.14,len=size*(.65+sp*.95)*(i%2?1:.85);ctx.save();ctx.rotate(a);ctx.strokeStyle=`rgba(255,48,78,${.4+.55*sp})`;ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(len*.55,-size*.2,len,Math.sin(i)*size*.18);ctx.stroke();ctx.fillStyle=`rgba(255,202,72,${.5+.5*sp})`;ctx.beginPath();ctx.arc(len,Math.sin(i)*size*.18,1.7,0,Math.PI*2);ctx.fill();ctx.restore()}}ctx.fillStyle='rgba(125,0,15,.85)';ctx.beginPath();ctx.arc(0,0,size*.15,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(now){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const cinematic=now<cinematicUntil;if(cinematic){ctx.fillStyle='rgba(18,0,5,.24)';ctx.fillRect(0,0,w,h)}if(bloom>.02){const ax=anchor.x*w,ay=anchor.y*h,count=Math.max(1,Math.round(1+bloom*4));for(let i=0;i<count;i++){const spread=(i-(count-1)/2)*32,topY=ay-(85+i%2*24)*bloom,topX=ax+spread+wind*30;ctx.strokeStyle=`rgba(61,94,43,${.35+.55*bloom})`;ctx.lineWidth=2.2;ctx.beginPath();ctx.moveTo(ax,ay);ctx.quadraticCurveTo(ax+spread*.25,ay-40,topX,topY);ctx.stroke();drawFlower(topX,topY,22+bloom*22,(bloom-.18)*1.25+i*.04,cinematic)}}for(const q of particles){const a=clamp(q.life);ctx.save();ctx.globalAlpha=a;ctx.translate(q.x*w,q.y*h);if(q.kind==='pollen'){ctx.fillStyle='#ffd87a';ctx.beginPath();ctx.arc(0,0,1.6,0,Math.PI*2);ctx.fill()}else{ctx.rotate((q.x+q.y)*12);ctx.fillStyle='#d51b38';ctx.beginPath();ctx.ellipse(0,0,5,2.2,.4,0,Math.PI*2);ctx.fill()}ctx.restore()}drawButterfly(w,h);const g=ctx.createRadialGradient(w/2,h*.45,50,w/2,h*.5,Math.max(w,h)*.75);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.28)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
function drawButterfly(w,h){const b=butterfly,x=b.x*w,y=b.y*h,s=Math.min(w,h)*.045,flap=b.state==='resting'?.45+.15*Math.sin(b.phase*4):.22+.7*Math.abs(Math.sin(b.phase*16));ctx.save();ctx.translate(x,y);ctx.shadowColor='rgba(255,255,255,.55)';ctx.shadowBlur=12;ctx.fillStyle='rgba(255,255,255,.82)';for(const side of[-1,1]){ctx.save();ctx.scale(side,1);ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(s*.35,-s*flap,s*1.05,-s*.7,s*.8,s*.08);ctx.bezierCurveTo(s*.6,s*.62,s*.1,s*.45,0,0);ctx.fill();ctx.restore()}ctx.shadowBlur=0;ctx.strokeStyle='rgba(215,225,235,.8)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,-s*.1);ctx.lineTo(0,s*.45);ctx.stroke();ctx.restore()}
let frames=0,fpsStamp=performance.now();function loop(now){const dt=Math.min(.05,(now-lastTime)/1000);lastTime=now;updateTracking(now,dt);updateParticles(dt);draw(now);frames++;if(debugMode&&now-fpsStamp>500){ui.debug.textContent=`FPS ${Math.round(frames*1000/(now-fpsStamp))} · Bloom ${bloom.toFixed(2)} · Butterfly ${butterfly.state}`;ui.debug.classList.remove('hidden');frames=0;fpsStamp=now}raf=requestAnimationFrame(loop)}
function capture(){const out=document.createElement('canvas');out.width=1080;out.height=1920;const c=out.getContext('2d'),vw=video.videoWidth,vh=video.videoHeight,scale=Math.max(out.width/vw,out.height/vh),dw=vw*scale,dh=vh*scale;c.save();c.translate(out.width,0);c.scale(-1,1);c.drawImage(video,(out.width-dw)/2,(out.height-dh)/2,dw,dh);c.restore();c.drawImage(canvas,0,0,out.width,out.height);out.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`higanbana-${Date.now()}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')}
$('enter').onclick=start;$('retry').onclick=start;$('back').onclick=()=>show('landing');$('exit').onclick=()=>{stop();show('landing')};$('capture').onclick=capture;$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'♪':'♩';$('sound').classList.toggle('active',soundOn)};$('record').onclick=()=>alert('Composed video recording support varies by browser. Photo capture is enabled in this version.');$('flip').onclick=async()=>{facingMode=facingMode==='user'?'environment':'user';stop();await start()};
document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimationFrame(raf);else if(stream)raf=requestAnimationFrame(loop)});
